#!/bin/csh -fex

set SKY_COLOR = "0.589 0.696 0.939"

obj2rfm craftsman-welded.obj craftsman-welded.rfm \
    --reset-normal --crease-angle 50 \
    --debug

rfm_direct craftsman-welded.rfm craftsman-welded-direct.rfm \
    --sun-az 210 --sun-el 30 \
    --debug

rfm_indirect craftsman-welded-direct.rfm craftsman-welded-indirect.rfm \
    --samples-per-vertex 100 \
    --error-tolerance 0.01 \
    --min-edge-length 0.1 \
    --max-pass 1 \
    --sky-color $SKY_COLOR \
    --direct-illumination-scale 0.7 \
    --diffuse-coefficient 0.45 \
    --bounces 3 \
    --debug

rfm2wrl craftsman-welded-indirect.rfm craftsman-welded-indirect.wrl \
    --sky-color $SKY_COLOR \
    --debug

open craftsman-welded-indirect.wrl
