#!/bin/csh -fx

set SKY_COLOR = "0.2 0.2 0.2"

set BIN_DIR = "/Users/drew/retro/bin"

obj2rfm color-bleeding.obj color-bleeding.rfm \
        --reset-normal --crease-angle 50 \
        --debug

/usr/bin/time rfm_direct color-bleeding.rfm color-bleeding-direct.rfm \
        --sun-az -100 --sun-el 30 \
        --debug

/usr/bin/time rfm_indirect color-bleeding-direct.rfm color-bleeding-indirect.rfm \
        --samples-per-vertex 100 \
        --error-tolerance 0.01 \
        --min-edge-length 0.1 \
        --max-pass 1 \
        --sky-color $SKY_COLOR \
        --direct-illumination-scale 0.6 \
        --diffuse-coefficient 0.5 \
        --bounces 3 \
        --debug

rfm2wrl color-bleeding-indirect.rfm color-bleeding-indirect.wrl \
        --sky-color $SKY_COLOR \
        --debug

open color-bleeding-indirect.wrl
