#!/bin/csh -f

if ($1 == "") then
    echo "Usage: $0:t revision [file]"
    echo "Which: Reverses the changes associated with the specified revision."
    echo "Options:"
    echo "    If no file is specified, all files in and below the current"
    echo "    directory are affected." 
    exit
endif

set revision = $1

set file = $2
if ("$file" == "") then
    set file = "."
endif

set command = "svn merge -c -$revision $file"

echo $command
$command
